package model;

/**
 * This is a parent class which will be applied to villages and
 * to the capital
 * @author zeno
 *
 */
public class Settlement {
	private int revenue, locationX, locationY;
	private EnemyParty party;
	
	/**
	 * Constructor for the class
	 * @param rev the revenue generated by the settlement
	 * @param location the bottom left corner the settlement is located at
	 * @param p the enemy party stationed in that location
	 */
	public Settlement(int rev, int left, int right, EnemyParty p){
		revenue = rev;
		locationX = left;
		locationY = right;
		party = p;		
	}
	
	public int getRevenue(){
		return revenue;
	}
	public int getLocationX(){
		return locationX;
	}
	public int getLocationY(){
		return locationY;
	}
	public EnemyParty getParty(){
		return party;
	}
	
	public void setRevenue(int rev){
		revenue = rev;
	}
	public void setLocation(int x, int y){
		locationX = x;
		locationY = y;
	}
	public void setParty(EnemyParty p){
		party = p;
	}
}